version: '{build}'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

image:
- Ubuntu
- Visual Studio 2019

configuration:
- Release
- Debug

platform:
- x64
#- x86 # by design PS4Delta can't support x86 systems

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  install:
    - |
      git submodule update --init --recursive
      set QT_DIR=C:\Qt\5.14.0\msvc2017_64
      pmake.bat
  build:
    project: build/PS4Delta.sln
    parallel: true
    verbosity: minimal
  after_build:
    - 7z a Artifacts.zip .\bin\*
  artifacts:
    - path: Artifacts.zip

-
  matrix:
    only:
      - image: Ubuntu
  install:
    - |
      git submodule update --init --recursive
      export QT_DIR=/usr/lib/x86_64-linux-gnu
      chmod +x ./pmake.sh
      ./pmake.sh
  build_script:
    - |
      cd build
      if [ "$CONFIGURATION" = "Release" ]; then
        make config=release_x64
      else
        make config=debug_x64
      fi

test: off
